name: filmmate
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  custom_refresh_indicator: ^4.0.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_displaymode: ^0.6.0
  flutter_dotenv: ^5.1.0
  flutter_exit_app: ^1.1.4
  flutter_hooks: ^0.21.2
  flutter_native_splash: ^2.4.0
  fquery: ^1.4.0-beta.1
  http: ^1.2.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  motion_toast: ^2.11.0
  open_file: ^3.5.10
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.3.1
  skeletonizer: ^1.4.1+1
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  json_serializable: ^6.8.0
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - .env

    - assets/images/

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply
