name: filmmate_flutter_app
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - .env

lint_staged:
  "lib/**.dart": dart fix --apply
