name: filmmate_flutter_app
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.6
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.6
  json_annotation: ^4.9.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.6
  json_serializable: ^6.8.0
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart fix --apply
