name: filmmate_flutter_app
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  http: ^1.2.1
  intl: ^0.19.0
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7
  json_serializable: ^6.8.0
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

lint_staged:
  "lib/**.dart": dart fix --apply
