name: filmmate_flutter_app
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart fix --apply
