name: filmmate_flutter_app
description: "Movie Recommendation App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  custom_refresh_indicator: ^3.1.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.0
  fquery: ^1.4.0-beta.1
  http: ^1.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  lint_staged: ^0.5.1

dependency_overrides:
  # analyzer: ^6.7.0
  js: ^0.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply
